// File generated by FlutterFire CLI (dev flavor).
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for the "dev" flavor's Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptionsDev.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptionsDev have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptionsDev have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptionsDev have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptionsDev have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptionsDev are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEpR4Znn-OgXtsW0T8Vwiq2zuJv2n-rmw',
    appId: '1:67152466070:ios:8ac3e4fdd11d3688c8b2b7',
    messagingSenderId: '67152466070',
    projectId: 'vocabulaire-test',
    storageBucket: 'vocabulaire-test.firebasestorage.app',
    iosBundleId: 'me.gregorgott.vocabulaire.dev',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEpR4Znn-OgXtsW0T8Vwiq2zuJv2n-rmw',
    appId: '1:67152466070:ios:8ac3e4fdd11d3688c8b2b7',
    messagingSenderId: '67152466070',
    projectId: 'vocabulaire-test',
    storageBucket: 'vocabulaire-test.firebasestorage.app',
    iosBundleId: 'me.gregorgott.vocabulaire.dev',
  );
}
